{% set name = "albucore" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/albucore-{{ version }}.tar.gz
  sha256: 8146982b428edc2f0affbffe36209143355410cdd05b9ed33d4b708b496574c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    # https://github.com/albumentations-team/albucore/issues/34
    - numpy >=1.24.4,<2
    - tomli >=2.0.1
    - typing-extensions >=4.9.0
    - opencv >=4.9.0

test:
  imports:
    - albucore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/albumentations-team/albucore
  summary: A high-performance image processing library designed to optimize and extend the Albumentations library with specialized functions for advanced image transformations. Perfect for developers working in computer vision who require efficient and scalable image augmentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdraw
    - ternaus
