{% set name = "albucore" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/albucore-{{ version }}.tar.gz
  sha256: f2cab5431fadf94abf87fd0c89d9f59046e49fe5de34afea8f89bc8390253746

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.4
    - typing-extensions >=4.9.0
    - opencv >=4.9.0
    - stringzilla >=3.10.4
    - simsimd >=5.9.2

test:
  imports:
    - albucore
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/albumentations-team/albucore
  summary: A high-performance image processing library designed to optimize and extend the Albumentations library with specialized functions for advanced image transformations. Perfect for developers working in computer vision who require efficient and scalable image augmentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
    - mdraw
    - ternaus
