{% set name = "albucore" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/albucore-{{ version }}.tar.gz
  sha256: e9956ac4debc47e804f0677ff4e23939ba322986eac16e801f8ea1c98269db65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24.4
    - tomli >=2.0.1
    - typing-extensions >=4.9.0
    - opencv >=4.9.0

test:
  imports:
    - albucore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/albumentations-team/albucore
  summary: A high-performance image processing library designed to optimize and extend the Albumentations library with specialized functions for advanced image transformations. Perfect for developers working in computer vision who require efficient and scalable image augmentation.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdraw
    - ternaus
